title: Simone Casolo # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Manager and industrial data scientist.</br>  
  I apply data science to solve problems in the heavy industry, 
  especially topological methods.</br>  
  <br><br>
  Currently working at Cognite. </br> 
  Ph.D. in theoretical chemistry.
  <br><br>
  <a href="https://www.linkedin.com/in/simone-casolo-6468a324/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
