title: Simone Casolo # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Manager and industrial data scientist.</br>  
  I apply artificial intelligence and machine learning to solve problems for the heavy industry. 
  My speciality is topological methods.</br>  
  <br>
   
  Currently working at <a href="https://www.cognite.com">Cognite.</a> </br> 
  Ph.D. in theoretical chemistry from <a href="https://www.unimi.it/en">University of Milan.</a> </br>
  </br></br>
  <a href="https://www.linkedin.com/in/simone-casolo-6468a324/">View my LinkedIn Profile</a> </br>
  <a href="https://scholar.google.com/citations?user=l9E9Zs4AAAAJ&hl=en&authuser=1">View my Google Scholar Profile</a>    </br>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
